name: Connect to GCP and List Instances

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: 'flowing-precept-409007'

jobs:
  setup-prepare-manifests-deploy:
    name: Setup, Prepare, and Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/345060966647/locations/global/workloadIdentityPools/githubactions/providers/github'
          service_account: 'github-action@flowing-precept-409007.iam.gserviceaccount.com'

    # List the instances in the project
    - name: List Instances
      run: |-
        gcloud compute instances list --project 'flowing-precept-409007'
  
     - id: 'gcloud'
       name: 'gcloud'
       run: gcloud secrets versions access "latest" --secret "my-secret"


