name: get secrets from secret manager

on:
  workflow_dispatch

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}

jobs:
  get-secrets:
     runs-on: ubuntu-latest
    # Allow the job to fetch a GitHub ID token
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    # List the instances in the project
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
  
     - id: 'gcloud'
       name: 'gcloud'
       run: gcloud secrets versions access "latest" --secret "my-secret"
